# Generated by Django 4.2.30 on 2026-05-14 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchRail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rail_type', models.CharField(choices=[('50-foot 1515', 'Fifty Foot 1515'), ('20-foot 1515', 'Twenty Foot 1515'), ('10-foot 1010', 'Ten Foot 1010'), ('10-foot 1515', 'Ten Foot 1515'), ('Auley', 'Auley'), ('Microcosm', 'Microcosm'), ('Newman', 'Newman'), ('Baxter', 'Baxter'), ('Own Rail', 'Self')], max_length=15)),
                ('location', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('G', 'Green Flag'), ('Y', 'Yellow Flag'), ('R', 'Red Flag')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('team_identifier', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], max_length=1)),
                ('engine_type', models.CharField(choices=[('H', 'Hybrid'), ('L', 'Liquid')], max_length=1)),
                ('fuel_oxidizer', models.TextField(blank=True, null=True)),
                ('target_altitude', models.IntegerField(blank=True, null=True)),
                ('gps_frequencies', models.JSONField(blank=True, default=list, null=True)),
                ('recovery_coordinates', models.JSONField(blank=True, default=list, null=True)),
                ('bunker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team_tracking.bunker')),
                ('launch_rail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team_tracking.launchrail')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AS', 'Absent'), ('OS', 'Onsite'), ('AR', 'At rail'), ('IS', 'In salvo'), ('IR', 'In recovery'), ('RD', 'Recovered')], max_length=2)),
                ('pad_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='team_tracking.team')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_tracking.team')),
            ],
        ),
        migrations.CreateModel(
            name='RailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IU', 'In Use'), ('FR', 'Free')], max_length=2)),
                ('launch_rail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_tracking.launchrail')),
            ],
        ),
    ]
