# Generated by Django 4.2.30 on 2026-05-27 02:36

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="category",
            field=models.CharField(
                choices=[
                    ("A", "Category A"),
                    ("B", "Category B"),
                    ("C", "Category C"),
                    ("E", "Category Ex"),
                ],
                max_length=1,
            ),
        ),
    ]
