# Generated by Django 5.2.14 on 2026-05-28 16:10

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0002_alter_team_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recoverypiece",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
