# Generated by Django 5.2.14 on 2026-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0003_increase_recovery_piece_name_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recoverypiece",
            name="lat",
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name="recoverypiece",
            name="lon",
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
