# Generated by Django 5.2.14 on 2026-05-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0005_trajectory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalvoSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lane_definitions", models.JSONField(default=list)),
                ("lane_teams", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
