# Generated by Django 5.2.14 on 2026-06-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0006_salvoschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="fill_to_fire",
            field=models.FloatField(
                blank=True, help_text="Fill-to-fire time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="hold_time",
            field=models.FloatField(
                blank=True, help_text="Hold time in minutes", null=True
            ),
        ),
    ]
