# Generated by Django 5.2.14 on 2026-06-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0007_add_timing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="fill_to_fire",
            field=models.FloatField(
                default=0.0, help_text="Fill-to-fire time in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="hold_time",
            field=models.FloatField(default=0.0, help_text="Hold time in minutes"),
        ),
    ]
