# Generated by Django 5.2.14 on 2026-06-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0008_timing_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="salvoschedule",
            name="team_data",
            field=models.JSONField(default=dict),
        ),
    ]
