# Generated by Django 5.2.14 on 2026-06-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0009_team_data_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="salvo_time",
            field=models.IntegerField(
                default=0, help_text="Assigned time-slot index (0=0min, 1=2min, …)"
            ),
        ),
    ]
