# Generated by Django 5.2.14 on 2026-06-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0010_salvo_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="salvoschedule",
            name="salvo_timer_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
