# Generated by Django 5.2.15 on 2026-06-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_tracking", "0011_salvoschedule_salvo_timer_started"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("team_identifier", models.CharField(max_length=10)),
                ("data", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
